/**
 * Lethean Server
 * Lethean dAppServer
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@lt.hn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateFileDTO { 
    path: string;
    data: string;
}

