// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserSelectedDirectoryPath():Promise<string>;

export function GetUserSelectedFilePath():Promise<string>;

export function GetUserSelectedSaveFilePath(arg1:string):Promise<string>;
